### ISSUE TITLE
Fixing documentation

### ISSUE THREAD

**Issue by FiV0** [russell/cl-git#36]
Is it possible to fix the doc or should the project be considered dead? I tried a bit, but I end up going deeper and deeper down the rabbit hole with sphinx problems accumulating.

**Comment by russell** [comment]
Yeah, not sure what to do with it yet...

I know another dev forked the cldomain project and started developing on it. So i'll take a look, if it's easy to resurrect, i will, otherwise i'll port it to another documentation system

**Comment by russell** [comment]
OK, so the documentation system has been resurrected, ported to roswell, and i put an effort into expanding the tests for that project because it suffered from AST magic numbers e.g. `node[0][0]` which made it pretty unapproachable.  It now has tests that verify the AST so it should be easier to hack on.

If you see issues with it feel free to raise bugs

**Comment by russell** [comment]
Sorry I should have said, the documentation is live again at https://russell.github.io/cl-git/ and is updated on merge to master
