### ISSUE TITLE
libgit2 incompatibility?

### ISSUE THREAD

**Issue by quicklisp** [russell/cl-git#41]
Hi, this recently stopped building for me, I get warnings on my system about undefined symbols:

    <path>/cl-git-20221101-git/src/libgit2-types-grovel0__grovel.c: In function ‘main’:
    <path>/cl-git-20221101-git/src/libgit2-types-grovel0__grovel.c:271:41: error: ‘GIT_CHECKOUT_DRY_RUN’ undeclared (first use in this function); did you mean ‘GIT_CHECKOUT_USE_OURS’?
       fprintf(output, "%"PRIiMAX, (intmax_t)GIT_CHECKOUT_DRY_RUN);
					     ^~~~~~~~~~~~~~~~~~~~
					     GIT_CHECKOUT_USE_OURS
    <path>/cl-git-20221101-git/src/libgit2-types-grovel0__grovel.c:271:41: note: each undeclared identifier is reported only once for each function it appears in
    <path>/cl-git-20221101-git/src/libgit2-types-grovel0__grovel.c:583:41: error: ‘GIT_DIFF_IGNORE_BLANK_LINES’ undeclared (first use in this function); did you mean ‘GIT_DIFF_IGNORE_CASE’?
       fprintf(output, "%"PRIiMAX, (intmax_t)GIT_DIFF_IGNORE_BLANK_LINES);
					     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
					     GIT_DIFF_IGNORE_CASE
    <path>/cl-git-20221101-git/src/libgit2-types-grovel0__grovel.c:745:41: error: ‘GIT_CREDENTIAL_USERPASS_PLAINTEXT’ undeclared (first use in this function); did you mean ‘GIT_CREDTYPE_USERPASS_PLAINTEXT’?
       fprintf(output, "%"PRIiMAX, (intmax_t)GIT_CREDENTIAL_USERPASS_PLAINTEXT);
					     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
					     GIT_CREDTYPE_USERPASS_PLAINTEXT
    <path>/cl-git-20221101-git/src/libgit2-types-grovel0__grovel.c:755:41: error: ‘GIT_CREDENTIAL_SSH_KEY’ undeclared (first use in this function); did you mean ‘GIT_CREDTYPE_SSH_KEY’?
       fprintf(output, "%"PRIiMAX, (intmax_t)GIT_CREDENTIAL_SSH_KEY);
					     ^~~~~~~~~~~~~~~~~~~~~~
					     GIT_CREDTYPE_SSH_KEY
    <path>/cl-git-20221101-git/src/libgit2-types-grovel0__grovel.c:765:41: error: ‘GIT_CREDENTIAL_SSH_CUSTOM’ undeclared (first use in this function); did you mean ‘GIT_CREDTYPE_SSH_CUSTOM’?
       fprintf(output, "%"PRIiMAX, (intmax_t)GIT_CREDENTIAL_SSH_CUSTOM);
					     ^~~~~~~~~~~~~~~~~~~~~~~~~
					     GIT_CREDTYPE_SSH_CUSTOM
    <path>/cl-git-20221101-git/src/libgit2-types-grovel0__grovel.c:775:41: error: ‘GIT_CREDENTIAL_DEFAULT’ undeclared (first use in this function); did you mean ‘GIT_CREDTYPE_DEFAULT’?
       fprintf(output, "%"PRIiMAX, (intmax_t)GIT_CREDENTIAL_DEFAULT);
					     ^~~~~~~~~~~~~~~~~~~~~~
					     GIT_CREDTYPE_DEFAULT
    <path>/cl-git-20221101-git/src/libgit2-types-grovel0__grovel.c:785:41: error: ‘GIT_CREDENTIAL_SSH_INTERACTIVE’ undeclared (first use in this function); did you mean ‘GIT_CREDTYPE_SSH_INTERACTIVE’?
       fprintf(output, "%"PRIiMAX, (intmax_t)GIT_CREDENTIAL_SSH_INTERACTIVE);
					     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
					     GIT_CREDTYPE_SSH_INTERACTIVE
    <path>/cl-git-20221101-git/src/libgit2-types-grovel0__grovel.c:795:41: error: ‘GIT_CREDENTIAL_USERNAME’ undeclared (first use in this function); did you mean ‘GIT_CREDTYPE_USERNAME’?
       fprintf(output, "%"PRIiMAX, (intmax_t)GIT_CREDENTIAL_USERNAME);
					     ^~~~~~~~~~~~~~~~~~~~~~~
					     GIT_CREDTYPE_USERNAME
    <path>/cl-git-20221101-git/src/libgit2-types-grovel0__grovel.c:805:41: error: ‘GIT_CREDENTIAL_SSH_MEMORY’ undeclared (first use in this function); did you mean ‘GIT_CREDTYPE_SSH_MEMORY’?
       fprintf(output, "%"PRIiMAX, (intmax_t)GIT_CREDENTIAL_SSH_MEMORY);
					     ^~~~~~~~~~~~~~~~~~~~~~~~~
					     GIT_CREDTYPE_SSH_MEMORY

I can't easily get the latest version of libgit2 and headers - is it possible to remain compatible with older versions?

**Comment by russell** [comment]
Potentially, but it would be hard.  It's not only constants that are changing but also entire function signatures.  I updated the library to use grovelling to help make maintenance of the library easier.  the 1.3.0 version that i currently support is not even the most recent, debian sid now has 1.5.0.

What version of libgit2 do you have? What is the OS?

What is the usecase? I'm assuming this is for quicklisp? do you only need to compile and load cl-git? do you need to run the cl-git tests? is it an actual application?

**Comment by quicklisp** [comment]
This is to build for including in the Quicklisp dist. I'm using the Linux
Debian 10 libgit2-dev package, which says it's version 0.27.7+dfsg.1-0.2.

**Comment by russell** [comment]
OK, that is quite an old version.

as i mentioned, it is probably possible to support multiple versions of the library, the high level api hasn't changed that much, it's the lowlevel stuff that changes.  But this has never been a priority for me, i have just been targeting the current version in sid.  I never thought it would be a problem since lots of software is shipped in docker containers these days.

It would be easier for me to implement from this version onward rather than retroactively adding it.

I'm not entire sure of how to implement multiple versions with CFFI and `grovel` files. maybe i can choose a file depending on the detected version of libgit2, so have multiple grovel files, one for each version.

I imagine that updating the quicklisp base OS is a lot of unplanned work for you, the current version in debian stable is 1.1.0, I'm assuming that you would eventually want to upgrade to the latest stable, that would mean i would need to potentially support 0.27.7, 1.1.0 and 1.5.0 at the very least.

The only other options i can think of are:
* Is there someway for me to compile libgit2 as part of the ASDF load, so that i can choose the version that is loaded with the CL library?
* Would it be reasonable/possible to disable compilation of some parts of the system when being loaded for the purpose of gathering metadata for quicklisp?

What are your thoughts?  I'm not opposed to supporting multiple versions, but it will take a fair bit of effort, and tbh, i don't know if i'm the only user of the library...

**Comment by vindarel** [comment]
(As soon as you create a new tag or release there will be more users :) )
